### ISSUE TITLE
Download any video on Instagram-An error occurred, please try again!

### ISSUE THREAD

**Issue by onlinedear** [xgetter-team/xgetter#1]
![WX20240624-112911@2x](https://github.com/xgetter-team/xgetter/assets/10751712/05519bd1-b6e6-4bd2-8aaa-ca1cf3c028f0)

**Comment by thanhtaivtt** [comment]
Thank you for submitting your request. Currently our logic is only supporting user posts (`https://www.instagram.com/p/xxxxx`).
While waiting for the upcoming release, you can download the reel video by editing the URL.
For example:
`https://www.instagram.com/reels/C7IDxOZS9ar` to `https://www.instagram.com/p/C7IDxOZS9ar`

We will fix this error in the upcoming version `1.1.9`.
Thank you again for informing us.

**Comment by thanhtaivtt** [comment]
We have fixed this error in version `1.1.9`. You can download or update the version to use.
