### ISSUE TITLE
I cannot download any videos

### ISSUE THREAD

**Issue by Crabor** [xgetter-team/xgetter#4]
**Describe the bug**
I cannot download any videos. your app sucks. I just purchased your app！

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://github.com/user-attachments/assets/5daf203e-bea4-469e-b4e3-f67a09ae38b3)
![image](https://github.com/user-attachments/assets/4159bf42-c45e-44cb-bedc-17f497b6245d)
![image](https://github.com/user-attachments/assets/094382d9-03bd-4109-9ad8-3c8795701b32)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] macOS

**Additional context**

**Comment by thanhtaivtt** [comment]
Hello,

First of all, we apologize for the inconvenience.

Here are the errors you encountered:

1. Bilibil is having trouble downloading (2 days ago). We have fixed it and are currently testing (expected to release early next week).

2. For Youtube, you need to remove the `t` parameter in the URL (in your case, remove `t=308s`).

3. For X (Twitter), we do not support downloading posts with more than 1 Video (will support it in future releases).

Many Thanks!

**Comment by thanhtaivtt** [comment]
Hello @Crabor ,
We have now fixed errors 1 and 2. Please update to version 1.3.1 to use.

Thank you for using XGetter
